#
#  project.yml
#  BChatbot
#
#  Created by badr_hourimeche on 6/3/2025.



name: BChatbot
options:
  bundleIdPrefix: ma.inwi
  deploymentTarget:
    iOS: 14.0
targets:
  Chatbot:
    type: framework
    platform: iOS
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ma.inwi.BChatbot
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      ENABLE_BITCODE: NO
